export const moduleCatalog = [
  {
    moduleKey: 'invoice-recovery-archive',
    name: '发票追索与归档整理',
    category: 'enterprise',
    description: '自动收集发票、识别票据信息并按规则归档，支持回款追索提醒。',
    icon: 'Tickets',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'debt-evidence-manager',
    name: '欠款证据管家',
    category: 'enterprise',
    description: '汇总合同、聊天记录、转账证明，自动形成可追踪证据链。',
    icon: 'DocumentChecked',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'enterprise-marketing-automation',
    name: '企业营销全自动',
    category: 'enterprise',
    description: '营销策略自动编排，覆盖线索触达、投放执行与复盘报告。',
    icon: 'TrendCharts',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'public-opinion-monitoring',
    name: '企业舆情监控',
    category: 'enterprise',
    description: '持续监听品牌舆情动态，风险分级并即时推送预警。',
    icon: 'Bell',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'lead-capture-followup',
    name: '企业线索抓取与跟进',
    category: 'enterprise',
    description: '自动收集意向客户线索并按优先级安排跟进任务。',
    icon: 'Search',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'private-domain-operations',
    name: '企业私域自动运营',
    category: 'enterprise',
    description: '自动执行私域分层运营策略，提高客户留存和复购。',
    icon: 'Connection',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'competitor-monitoring',
    name: '企业竞品监控',
    category: 'enterprise',
    description: '跟踪竞品价格、活动与内容策略，自动输出对比摘要。',
    icon: 'Histogram',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'data-retrospective-automation',
    name: '企业数据复盘自动化',
    category: 'enterprise',
    description: '自动聚合经营数据，生成阶段复盘结论与优化建议。',
    icon: 'DataLine',
    status: 'beta',
    mobileSupported: true,
  },
  {
    moduleKey: 'matchmaking-ai',
    name: '高学历相亲 AI 自动匹配',
    category: 'personal',
    description: '基于偏好与约束条件自动匹配候选人，并推送提醒。',
    icon: 'User',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'product-health-check',
    name: 'AI 商品体检',
    category: 'personal',
    description: '上传商品图片与信息，自动输出风险项和建议等级。',
    icon: 'Camera',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'anti-fraud-guardian',
    name: '个人反诈守护',
    category: 'personal',
    description: '识别可疑话术、链接与账号行为，提示潜在诈骗风险。',
    icon: 'Lock',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'personal-invoice-manager',
    name: '个人发票管理',
    category: 'personal',
    description: '自动归类个人票据，支持快速检索和报销前预检查。',
    icon: 'Document',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'teacher-knowledge-monetization',
    name: '教师知识库 + 投稿变现',
    category: 'personal',
    description: '沉淀教学资料并自动生成投稿草案，提升产出效率。',
    icon: 'Reading',
    status: 'beta',
    mobileSupported: true,
  },
  {
    moduleKey: 'job-lead-capture',
    name: '个人求职线索自动抓取',
    category: 'personal',
    description: '自动抓取职位线索并按匹配度整理投递优先级。',
    icon: 'Briefcase',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'content-auto-publishing',
    name: '个人内容自动生成与发布',
    category: 'personal',
    description: '按内容主题自动生成多平台文案并计划发布节奏。',
    icon: 'EditPen',
    status: 'active',
    mobileSupported: true,
  },
]

export const moduleExecutionRules = {
  'invoice-recovery-archive': {
    focusChecks: ['票据完整性校验', '归档目录一致性', '追索时效提醒'],
    riskSignals: ['缺失', '错票', '逾期', '无法识别', '冲红'],
    failSignals: ['票据损坏', '解析失败'],
    nextActions: ['补齐缺失票据后重新执行归档。', '将高风险票据加入追索清单并设置提醒。'],
  },
  'debt-evidence-manager': {
    focusChecks: ['证据链连续性', '时间线一致性', '关键凭证覆盖率'],
    riskSignals: ['证据不足', '争议', '缺少合同', '缺少转账'],
    failSignals: ['证据冲突', '时间线断裂'],
    nextActions: ['补充合同与交易记录，确保时间线完整。', '对争议条目追加人工复核备注。'],
  },
  'enterprise-marketing-automation': {
    focusChecks: ['触达节奏有效性', '渠道投放匹配度', '转化漏斗健康度'],
    riskSignals: ['转化低', '点击低', '预算超支', '渠道异常'],
    failSignals: ['投放失败', '渠道不可用'],
    nextActions: ['优先调整低转化渠道的投放策略。', '对核心场景增加 A/B 测试。'],
  },
  'public-opinion-monitoring': {
    focusChecks: ['舆情来源可信度', '负面话题聚类', '预警响应时效'],
    riskSignals: ['投诉', '负面', '危机', '曝光', '维权'],
    failSignals: ['舆情源不可达'],
    nextActions: ['对高热负面话题启用加急响应。', '将重复舆情归并并追踪处置结果。'],
  },
  'lead-capture-followup': {
    focusChecks: ['线索去重率', '跟进时效', '成交概率评分'],
    riskSignals: ['无效线索', '重复', '失联', '超时'],
    failSignals: ['线索抓取失败'],
    nextActions: ['优先跟进高评分线索，缩短首次响应时间。', '清理重复和低质量线索。'],
  },
  'private-domain-operations': {
    focusChecks: ['人群分层准确性', '触达频率控制', '复购提升趋势'],
    riskSignals: ['退订', '流失', '触达过频'],
    failSignals: ['触达引擎异常'],
    nextActions: ['对流失人群单独制定挽回策略。', '减少高频触达，避免用户疲劳。'],
  },
  'competitor-monitoring': {
    focusChecks: ['竞品价格波动', '活动策略变化', '内容节奏差异'],
    riskSignals: ['降价', '抢量', '活动升级'],
    failSignals: ['竞品数据源异常'],
    nextActions: ['对重点竞品波动设置即时告警。', '结合本方资源制定应对策略。'],
  },
  'data-retrospective-automation': {
    focusChecks: ['指标完整度', '异常波动识别', '结论可执行性'],
    riskSignals: ['波动异常', '数据缺失', '口径冲突'],
    failSignals: ['聚合失败'],
    nextActions: ['补全缺失指标后重新复盘。', '将异常波动拆解到业务环节。'],
  },
  'matchmaking-ai': {
    focusChecks: ['偏好匹配度', '约束条件冲突', '候选池质量'],
    riskSignals: ['匹配不足', '条件冲突', '画像缺失'],
    failSignals: ['候选池为空'],
    nextActions: ['放宽次级条件以扩大候选池。', '补全资料后再次匹配。'],
  },
  'product-health-check': {
    focusChecks: ['商品信息完整性', '风险条目识别', '建议可执行性'],
    riskSignals: ['违规', '侵权', '质量风险', '描述不符'],
    failSignals: ['体检模型不可用'],
    nextActions: ['对高风险条目优先整改并复检。', '补充缺失资质信息。'],
  },
  'anti-fraud-guardian': {
    focusChecks: ['风险话术识别', '链接可信度校验', '账号行为异常检测'],
    riskSignals: ['转账', '验证码', '退款', '陌生链接', '诈骗'],
    failSignals: ['风控服务异常'],
    nextActions: ['出现高风险信号时立即中断交易流程。', '保留证据并进行人工核验。'],
  },
  'personal-invoice-manager': {
    focusChecks: ['票据分类准确性', '报销字段完整性', '重复票据识别'],
    riskSignals: ['重复', '抬头错误', '税号异常'],
    failSignals: ['票据识别失败'],
    nextActions: ['修正抬头和税号后重新校验。', '清理重复票据并归档。'],
  },
  'teacher-knowledge-monetization': {
    focusChecks: ['内容结构完整性', '投稿匹配度', '变现路径清晰度'],
    riskSignals: ['选题偏差', '重复投稿', '结构松散'],
    failSignals: ['投稿通道异常'],
    nextActions: ['按平台要求优化标题与摘要。', '围绕高反馈主题持续迭代内容。'],
  },
  'job-lead-capture': {
    focusChecks: ['职位匹配度', '投递优先级', '反馈跟踪完整性'],
    riskSignals: ['低匹配', '反馈滞后', '岗位过期'],
    failSignals: ['职位抓取失败'],
    nextActions: ['优先投递高匹配岗位并跟进结果。', '定期清理过期职位线索。'],
  },
  'content-auto-publishing': {
    focusChecks: ['内容质量稳定性', '发布节奏合理性', '平台适配度'],
    riskSignals: ['违规风险', '内容重复', '发布时间冲突'],
    failSignals: ['发布队列异常'],
    nextActions: ['调整发布时间窗提升触达。', '针对不同平台优化文案版本。'],
  },
}

export function getModuleName(moduleKey) {
  return moduleCatalog.find((item) => item.moduleKey === moduleKey)?.name ?? moduleKey
}

export function getModuleRule(moduleKey) {
  return (
    moduleExecutionRules[moduleKey] ?? {
      focusChecks: ['输入完整性', '结果可追溯性', '输出可执行性'],
      riskSignals: ['异常', '冲突', '缺失'],
      failSignals: ['处理失败'],
      nextActions: ['补充关键输入后重试。', '对异常项进行人工复核。'],
    }
  )
}
