export const platformModuleCatalog = [
  {
    moduleCode: 'marketing',
    moduleName: '企业营销自动化',
    moduleType: 'enterprise',
    routePath: '/modules/marketing',
    icon: 'TrendCharts',
    status: 'enabled',
    sort: 1,
    accessMode: 'tenant',
    description: '自动化营销任务编排与执行。',
  },
  {
    moduleCode: 'ad-monitor',
    moduleName: '广告监测与复盘',
    moduleType: 'enterprise',
    routePath: '/modules/ad-monitor',
    icon: 'DataAnalysis',
    status: 'enabled',
    sort: 2,
    accessMode: 'tenant',
    description: '广告投放监测与复盘分析。',
  },
  {
    moduleCode: 'content',
    moduleName: '内容生成中心',
    moduleType: 'enterprise',
    routePath: '/modules/content',
    icon: 'EditPen',
    status: 'enabled',
    sort: 3,
    accessMode: 'tenant',
    description: '内容生产、改写与发布建议。',
  },
  {
    moduleCode: 'leads',
    moduleName: '线索清洗与 CRM',
    moduleType: 'enterprise',
    routePath: '/modules/leads',
    icon: 'UserFilled',
    status: 'enabled',
    sort: 4,
    accessMode: 'tenant',
    description: '线索去重、评分与跟进管理。',
  },
  {
    moduleCode: 'public-opinion',
    moduleName: '舆情监控',
    moduleType: 'enterprise',
    routePath: '/modules/public-opinion',
    icon: 'Bell',
    status: 'enabled',
    sort: 5,
    accessMode: 'tenant',
    description: '品牌舆情监测与异常预警。',
  },
  {
    moduleCode: 'private-domain',
    moduleName: '私域运营',
    moduleType: 'enterprise',
    routePath: '/modules/private-domain',
    icon: 'Connection',
    status: 'developing',
    sort: 6,
    accessMode: 'tenant',
    description: '私域人群分层与自动触达。',
  },
  {
    moduleCode: 'live-control',
    moduleName: '直播场控',
    moduleType: 'enterprise',
    routePath: '/modules/live-control',
    icon: 'VideoPlay',
    status: 'developing',
    sort: 7,
    accessMode: 'tenant',
    description: '直播脚本、节奏与场控策略。',
  },
  {
    moduleCode: 'product-check',
    moduleName: '商品体检',
    moduleType: 'enterprise',
    routePath: '/modules/product-check',
    icon: 'Goods',
    status: 'developing',
    sort: 8,
    accessMode: 'tenant',
    description: '商品信息合规与表现诊断。',
  },
  {
    moduleCode: 'invoice',
    moduleName: '发票管理',
    moduleType: 'enterprise',
    routePath: '/modules/invoice',
    icon: 'Tickets',
    status: 'developing',
    sort: 9,
    accessMode: 'tenant',
    description: '发票归档、核验与检索。',
  },
  {
    moduleCode: 'matchmaking',
    moduleName: '相亲匹配',
    moduleType: 'personal',
    routePath: '/modules/matchmaking',
    icon: 'Star',
    status: 'developing',
    sort: 10,
    accessMode: 'tenant',
    description: '偏好匹配与候选推荐。',
  },
  {
    moduleCode: 'job-leads',
    moduleName: '求职线索',
    moduleType: 'personal',
    routePath: '/modules/job-leads',
    icon: 'Briefcase',
    status: 'developing',
    sort: 11,
    accessMode: 'tenant',
    description: '职位线索收集与投递管理。',
  },
  {
    moduleCode: 'anti-fraud',
    moduleName: '反诈识别',
    moduleType: 'personal',
    routePath: '/modules/anti-fraud',
    icon: 'Lock',
    status: 'developing',
    sort: 12,
    accessMode: 'tenant',
    description: '风险语义识别与诈骗预警。',
  },
  {
    moduleCode: 'campaign',
    moduleName: '活动执行',
    moduleType: 'enterprise',
    routePath: '/modules/campaign',
    icon: 'Flag',
    status: 'developing',
    sort: 13,
    accessMode: 'tenant',
    description: '活动流程编排与执行监控。',
  },
  {
    moduleCode: 'analytics',
    moduleName: '数据分析中心',
    moduleType: 'platform',
    routePath: '/modules/analytics',
    icon: 'PieChart',
    status: 'developing',
    sort: 14,
    accessMode: 'tenant',
    description: '跨模块统计分析与洞察。',
  },
  {
    moduleCode: 'ai-assistant',
    moduleName: '通用 AI 助手',
    moduleType: 'platform',
    routePath: '/modules/ai-assistant',
    icon: 'MagicStick',
    status: 'developing',
    sort: 15,
    accessMode: 'tenant',
    description: '统一 AI 对话与执行入口。',
  },
]

export const platformRoleCatalog = [
  { roleCode: 'platform_super_admin', roleName: '平台超级管理员' },
  { roleCode: 'platform_operator_admin', roleName: '平台运营管理员' },
  { roleCode: 'customer_admin', roleName: '客户管理员' },
  { roleCode: 'customer_member', roleName: '客户普通成员' },
  { roleCode: 'read_only', roleName: '只读账号' },
]

export const platformPermissionCatalog = [
  { permCode: 'dashboard.view', permName: '查看首页' },
  { permCode: 'task.view', permName: '查看任务' },
  { permCode: 'task.create', permName: '创建任务' },
  { permCode: 'task.export', permName: '导出任务数据' },
  { permCode: 'message.view', permName: '查看消息' },
  { permCode: 'message.read', permName: '消息已读' },
  { permCode: 'module.view', permName: '查看模块' },
  { permCode: 'module.open', permName: '模块开通管理' },
  { permCode: 'report.view', permName: '查看报表' },
  { permCode: 'report.export', permName: '导出报表' },
  { permCode: 'settings.view', permName: '查看系统设置' },
  { permCode: 'settings.update', permName: '修改系统设置' },
]

export const platformMenuCatalog = [
  { menuCode: 'dashboard', menuName: '首页仪表盘', routePath: '/dashboard', icon: 'HomeFilled', sort: 1 },
  { menuCode: 'task-center', menuName: '任务中心', routePath: '/task-center', icon: 'List', sort: 2 },
  { menuCode: 'message-center', menuName: '消息中心', routePath: '/message-center', icon: 'Bell', sort: 3 },
  { menuCode: 'module-center', menuName: '模块中心', routePath: '/module-center', icon: 'Grid', sort: 4 },
  { menuCode: 'customer-management', menuName: '客户管理', routePath: '/customer-management', icon: 'User', sort: 5 },
  { menuCode: 'package-management', menuName: '套餐管理', routePath: '/package-management', icon: 'Box', sort: 6 },
  { menuCode: 'reports', menuName: '数据报表', routePath: '/reports', icon: 'DataLine', sort: 7 },
  { menuCode: 'settings', menuName: '系统设置', routePath: '/settings', icon: 'Setting', sort: 8 },
]

