import type { ModuleMeta } from '@/types/domain'

export const moduleCatalog: ModuleMeta[] = [
  {
    moduleKey: 'invoice-recovery-archive',
    name: '发票追索与归档整理',
    category: 'enterprise',
    description: '自动收集发票、识别票据信息并按规则归档，支持回款追索提醒。',
    icon: 'Tickets',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'debt-evidence-manager',
    name: '欠款证据管家',
    category: 'enterprise',
    description: '汇总合同、聊天记录、转账证明，自动形成可追踪证据链。',
    icon: 'DocumentChecked',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'enterprise-marketing-automation',
    name: '企业营销全自动',
    category: 'enterprise',
    description: '营销策略自动编排，覆盖线索触达、投放执行与复盘报告。',
    icon: 'TrendCharts',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'public-opinion-monitoring',
    name: '企业舆情监控',
    category: 'enterprise',
    description: '持续监听品牌舆情动态，风险分级并即时推送预警。',
    icon: 'Bell',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'lead-capture-followup',
    name: '企业线索抓取与跟进',
    category: 'enterprise',
    description: '自动收集意向客户线索并按优先级安排跟进任务。',
    icon: 'Search',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'private-domain-operations',
    name: '企业私域自动运营',
    category: 'enterprise',
    description: '自动执行私域分层运营策略，提高客户留存和复购。',
    icon: 'Connection',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'data-retrospective-automation',
    name: '数据复盘自动化',
    category: 'enterprise',
    description: '自动聚合经营数据，生成阶段复盘结论与优化建议。',
    icon: 'DataLine',
    status: 'beta',
    mobileSupported: true,
  },
  {
    moduleKey: 'competitor-monitoring',
    name: '企业竞品监控',
    category: 'enterprise',
    description: '持续追踪竞品动态、版本变化与营销动作，辅助策略调整。',
    icon: 'Histogram',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'anti-fraud-guardian',
    name: '全域反诈守护',
    category: 'personal',
    description: 'AI 中老年健康信息净化器 + 防骗证据助手，支持风险识别、存证与投诉材料整理。',
    icon: 'Lock',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'smart-grocery-supermarket',
    name: '智慧买菜 / 超市',
    category: 'personal',
    description: '家庭买菜省钱 AI，支持比价、预算控餐、菜谱与特价提醒。',
    icon: 'Grid',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'personal-invoice-manager',
    name: '个人票证管理',
    category: 'personal',
    description: '自动归类个人票据，支持快速检索和报销前预检查。',
    icon: 'Document',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'matchmaking-assistant',
    name: '高学历相亲 AI 自动匹配',
    category: 'personal',
    description: '根据偏好与画像自动匹配候选对象，并生成沟通建议。',
    icon: 'User',
    status: 'beta',
    mobileSupported: true,
  },
  {
    moduleKey: 'product-health-check',
    name: 'AI 商品体检',
    category: 'personal',
    description: '分析商品卖点、标题与详情页表现，给出可执行优化建议。',
    icon: 'Camera',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'teacher-knowledge-monetization',
    name: '教师知识库 + 投稿变现',
    category: 'personal',
    description: '沉淀课程知识库，自动生成投稿素材与变现选题。',
    icon: 'Reading',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'job-lead-automation',
    name: '个人求职线索自动抓取',
    category: 'personal',
    description: '自动聚合职位线索并按优先级推荐投递与跟进计划。',
    icon: 'Briefcase',
    status: 'active',
    mobileSupported: true,
  },
  {
    moduleKey: 'content-generation-publisher',
    name: '个人内容自动生成与发布',
    category: 'personal',
    description: '自动生成多平台内容草稿并按计划发布与复盘。',
    icon: 'EditPen',
    status: 'active',
    mobileSupported: true,
  },
]

export const moduleMap = new Map(moduleCatalog.map((item) => [item.moduleKey, item]))
